### ISSUE TITLE
Issue Compiling on Windows

### ISSUE THREAD

**Issue by deviousdaemon** [bjorn/tiled#1279]
Every time I've tried to compile Tiled I get a LNK1104 error that "intermediate.tiled.exe.manifest" cannot be opened. I've tried compiling both the 64-bit and 32-bit version, reinstalled qt-5, and tried visual studio 2013 to no avail. Is there anything else I could try?

**Comment by bjorn** [comment]
Hmm, I've never heard of that problem before unfortunately. Two things that may help:

* Make sure to use `tiled.qbs` and not `tiled.pro`
* Use Qt 5.5 for now, since I didn't get around to making Tiled compile against Qt 5.6 yet (though the problem I'm running into is that since 5.6, the header file `<QtZlib/zlib.h>` is missing.

**Comment by deviousdaemon** [comment]
Well now I get an exit code 1 error where "windres.exe" has failed preprocessing. I think I may just stick the the itch.io build.

**Comment by bjorn** [comment]
Hmm, that's very strange. I've just recently installed Qt on a new Windows 10 install and simply chose Qt 5.5 for MinGW 4.9.2, plus Tools/MinGW 4.9.2 and it compiles Tiled fine.

I would expect the failed "windres.exe" only when using `tiled.pro` and not when using `tiled.qbs.`. You are trying to compile `master` right, rather than the 0.16.1 source files?

Note that if you're looking for a more recent build, there are snapshots available for Windows at http://update.mapeditor.org/snapshots-win/ (these are also linked from the itch.io download page).

**Comment by deviousdaemon** [comment]
Yes I have only been trying the tiled master branch and the tiled.qbs file but it's made no difference, only different errors.

**Comment by bjorn** [comment]
I've fixed the problem with zlib when compiling against Qt 5.6 + MinGW in change 4c8a4b7a1a332c30bf7a24e1b3f5ec93012df70e.

**Comment by bjorn** [comment]
For me and on AppVeyor, Tiled is now compiling fine when using `tiled.qbs` with either Qt for MinGW (32-bit) or Qt for Visual Studio 2013 (32-bit and 64-bit). Are you still having this "manifest could not be opened" issue?

**Comment by deviousdaemon** [comment]
Sorry for the late response, but yes I still can't build, even on a fresh install of windows. I've attached a pic to show the error I receive.
![tiled debug](https://cloud.githubusercontent.com/assets/16088704/15955189/a200b090-2e9c-11e6-8b19-32307754f757.png)

**Comment by bjorn** [comment]
Did you clone Tiled into a directory called "Builds", or what is happening here?

Please paste the output from the compiler rather than the extracted issues.

**Comment by deviousdaemon** [comment]
Ok here is the full compile output:

14:16:01: Running steps for project tiled...
compiling tiled.rc
compiling zoomable.cpp
compiling snaphelper.cpp
compiling languagemanager.cpp
compiling tilelayeritem.cpp
compiling objectselectionitem.cpp
compiling moc_tileanimationeditor.cpp
compiling moc_aboutdialog.cpp
compiling renameterrain.cpp
compiling filesystemwatcher.cpp
compiling layermodel.cpp
compiling moc_mapscene.cpp
C:/Qt/Tools/mingw530_32/bin/windres.exe -D NDEBUG -D UNICODE -D _UNICODE -D "TILED_VERSION=0.16.1" -D QT_NO_CAST_FROM_ASCII -D QT_NO_CAST_TO_ASCII -D QT_CORE_LIB -D QT_NO_DEBUG -D QT_GUI_LIB -D QT_NETWORK_LIB -D QT_OPENGL_LIB -D QT_WIDGETS_LIB -I "E:/Tiled Builds/src/tiled" -I C:/Qt/5.7/mingw53_32/include -I C:/Qt/5.7/mingw53_32/include/QtCore -I C:/Qt/5.7/mingw53_32/mkspecs/win32-g++ -I E:/build-tiled-Desktop_Qt_5_7_0_MinGW_32bit-Release/qtc_Desktop__cc5307a8-release/tiled.qtc-Desktop--cc5307a8.71721af6/GeneratedFiles -I C:/Qt/5.7/mingw53_32/include -I C:/Qt/5.7/mingw53_32/include/QtGui -I C:/Qt/5.7/mingw53_32/include/QtANGLE -I C:/Qt/5.7/mingw53_32/include -I C:/Qt/5.7/mingw53_32/include/QtNetwork -I C:/Qt/5.7/mingw53_32/include -I C:/Qt/5.7/mingw53_32/include/QtOpenGL -I C:/Qt/5.7/mingw53_32/include -I C:/Qt/5.7/mingw53_32/include/QtWidgets -I "E:/Tiled Builds/src/libtiled" -I "E:/Tiled Builds/src/qtpropertybrowser/src" -I "E:/Tiled Builds/src/qtsingleapplication/src" -i E:/build-tiled-Desktop_Qt_5_7_0_MinGW_32bit-Release/qtc_Desktop__cc5307a8-release/tiled.qtc-Desktop--cc5307a8.71721af6/GeneratedFiles/tiled.rc -o E:/build-tiled-Desktop_Qt_5_7_0_MinGW_32bit-Release/qtc_Desktop__cc5307a8-release/tiled.qtc-Desktop--cc5307a8.71721af6/.obj/39301be37a6f50b4/tiled_res.o
gcc: error: Builds/src/tiled: No such file or directory
gcc: error: Builds/src/libtiled: No such file or directory
gcc: error: Builds/src/qtpropertybrowser/src: No such file or directory
gcc: error: Builds/src/qtsingleapplication/src: No such file or directory
C:\Qt\Tools\mingw530_32\bin\windres.exe: preprocessing failed.
Process failed with exit code 1.
The following products could not be built for configuration qtc_Desktop__cc5307a8-release:
	automappingconverter
	tiled
	tmxrasterizer
	flare
	lua
Error while building/deploying project tiled (kit: Desktop Qt 5.7.0 MinGW 32bit)
When executing step "Qbs Build"
14:16:06: Elapsed time: 00:05.

**Comment by bjorn** [comment]
Ok, you're compiling with Qt 5.7, which I have not tested yet on Windows (Qt 5.7 is also not final yet). I have only just fixed things up to compile against Qt 5.6, and I would not be surprised if for some reason it won't compile with Qt 5.7, especially if you also throw in a much more recent version of MinGW (5.3) than I have used so far.

Unfortunately it is not immediately obvious to me what could be needed to get this `windres.exe` command to succeed.

For now, please stick with Qt 5.6 and MinGW 4.9.

**Comment by deviousdaemon** [comment]
That's the thing though, I didn't install QT 5.7, I specifically unchecked that and installed 5.6 instead.

**Comment by bjorn** [comment]
Ok, I just noticed the path you're using to compile Tiled in is "E:/Tiled Builds/src/tiled", and judging by the error messages, it cut off part of that path. Apparently, some tool is having trouble dealing correctly with spaces in paths (I'm guessing windres.exe, since it seems Qbs quoted things correctly and I'm sure gcc would generally deal with this fine too).

So, please extract Tiled sources to a path without spaces, then the build should really work fine.

**Comment by hassandraga** [comment]
I have the same issue with windres, version GNU windres (GNU Binutils) 2.28 (2017)

**Comment by bjorn** [comment]
@hassandraga Then please make sure you don't check out Tiled in a path than contains spaces.

**Comment by bjorn** [comment]
I just tested this with Qbs 1.13 and MinGW 7.3, but unfortunately it's still an issue.
